### PR TITLE
My review

### PR DESCRIPTION
**Pull request by KevCaz**
Hi Tom,

As part of my review of your manuscript that describes the package I have created this PR. I did minor change in the package and provide detailed suggestions.

Hope this will help.

### Change in the README.rmd header

I was not able to rebuild the pkdown webpage until I changed:

```
bibliography: "`r here::here('inst/REFERENCES.bib')`"
```

For:

```
bibliography: "inst/REFERENCES.bib
```

You may want to switch it back but now you know that it does not always work
(see my session info at the bottom of this PR).

### Web page 

I have rebuilt the, I think it is worth to add it to the GitHub page and mention it in the DESCRIPTION file.

### `&&` or `&`?

Most `&&` should be `&` and `||` must be `|`. Difference are explained
here (see https://stackoverflow.com/questions/16027840/whats-the-differences-between-and-and-in-r).
I exemplify this below:

```r
R>> c(TRUE, FALSE) & c(TRUE, FALSE)
[1]  TRUE FALSE
R>> c(TRUE, FALSE) && c(TRUE, FALSE)
[1] TRUE
R>> c(TRUE, FALSE) && c(TRUE, TRUE)
[1] TRUE
R>> c(TRUE, FALSE) && c(FALSE, TRUE)
[1] FALSE
```

In the package, it works fine because logical tests are made on vectors of length of 1, but it should be `&` and `|` unless you have a specific reason for using the long form. I changed some of them but not all.

## Suggestions

I did a couple of suggestions in the light of the developer guide of ROpenSci https://ropensci.github.io/dev_guide/.

### Unit testing

In my review (I guess you'll have in a couple of days), I make a strong case about unit testing and I hope you would add them in a upcoming version of the package. This is especially important if you want external contribution!

### Good practice  

[goodpractice](https://github.com/MangoTheCat/goodpractice) is extremely helpful to check whether your code is compliant to a certain style. For the current version of "sars", it returns the following suggestions (I run `goodpractice::gp(".")`):

```r
It is good practice to

  ✖ write unit tests for all functions, and all package code in general. 0% of code lines are covered by test cases.

    R/class_plot.R:75:NA
    R/class_plot.R:78:NA
    R/class_plot.R:79:NA
    R/class_plot.R:80:NA
    R/class_plot.R:81:NA
    ... and 1877 more lines

  ✖ use '<-' for assignment instead of '='. '<-' is the standard, and R users and developers are used it and it is easier to read
    your code for them if you use '<-'.

    inst/Dengler.R:186:12
    inst/Dengler.R:186:24
    inst/Dengler.R:196:7
    inst/Dengler.R:197:4
    inst/Dengler.R:199:3
    ... and 177 more lines

  ✖ avoid long code lines, it is bad for readability. Also, many people prefer editor windows that are about 80 characters wide. Try
    make your lines shorter than 80 characters

    inst/Dengler.R:19:1
    inst/Dengler.R:39:1
    inst/Dengler.R:50:1
    inst/Dengler.R:53:1
    inst/Dengler.R:54:1
    ... and 428 more lines


  ✖ avoid sapply(), it is not type safe. It might return a vector, or a list, depending on the input data. Consider using vapply()
    instead.

    inst/Dengler.R:146:15
    inst/Dengler.R:264:1
    inst/Dengler.R:264:29
    R/fit_collection.R:21:12

  ✖ avoid 1:length(...), 1:nrow(...), 1:ncol(...), 1:NROW(...) and 1:NCOL(...) expressions. They are error prone and result 1:0 if
    the expression on the right hand side is zero. Use seq_len() or seq_along() instead.

    inst/Dengler.R:281:11
    inst/Dengler.R:394:11
    R/class_plot.R:194:42
    R/class_plot.R:194:59
    R/class_plot.R:196:97
    ... and 13 more lines

  ✖ not import packages as a whole, as this can cause name clashes between the imported packages. Instead, import only the specific
    functions you need.
  ✖ fix this R CMD check WARNING: Found the following file(s) containing GNU extensions: Makefile Portable Makefiles do not use GNU
    extensions such as +=, :=, $(shell), $(wildcard), ifeq ... endif. See section ‘Writing portable packages’ in the ‘Writing R Extensions’
    manual.
  ✖ fix this R CMD check NOTE: installed size is 5.0Mb sub-directories of 1Mb or more: refs 4.3Mb
  ✖ avoid 'T' and 'F', as they are just variables which are set to the logicals 'TRUE' and 'FALSE' by default, but are not reserved
    words and hence can be overwritten by the user.  Hence, one should always use 'TRUE' and 'FALSE' for the logicals.

    R/class_plot.R:NA:NA
    R/class_plot.R:NA:NA
    R/mod_linear_power.R:NA:NA
    R/obs_shape.R:NA:NA
    R/obs_shape.R:NA:NA

```

### Code redundancy

Many parts of the code are redundant, I think it would be for the best if you could use helper functions to avoid redundancy (some developers use `zzz.R` to store such functions, see [taxize](https://github.com/ropensci/taxize) as an example). A good example of redundancy in your code are the first lines of the 20 `sars_*()`:

```r
if (!(is.matrix(data) || is.data.frame(data))) stop('data must be a matrix or dataframe')
if (is.matrix(data)) data <- as.data.frame(data)
if (anyNA(data)) stop('NAs present in data')
```

It would be better to create a function `helper_test_sar()` instead:

```r
helper_test_sar <- function(data) {
  if (!(is.matrix(data) | is.data.frame(data))) stop('data must be a matrix or dataframe')
  if (is.matrix(data)) data <- as.data.frame(data)
  if (anyNA(data)) stop('NAs present in data')
  data
}
```

By the way, I would rather recommend something like this:

```r
helper_test_sar <- function(data) {
  data <- as.data.frame(data)
  if (anyNA(data)) stop('NAs present in data')
  data
}
```

As it handles the two first lines above (and more) and if the conversion is not possible, an error action will be executed. You can be more restrictive like so:

```r
helper_test_sar <- function(data) {
  stopifnot(class(dtaa) %in% c("data.frame", "matrix"))
  data <- as.data.frame(data)
  if (anyNA(data)) stop('NAs present in data')
  data
}
```

Whatever the final function is, you could then use it instead of the blocks of three lines:

```R
data <- helper_test_sar(data)
```

29 characters instead of 185, and only one helper function to test!

### Simplify your messages!

Actually

```r
cat("\n", "Model fitting completed. Now undertaking model validation checks.", "\n", "Additional models will be excluded if necessary:", "\n")
```
is equivalent to:

```r
cat("\nModel fitting completed. Now undertaking model validation checks.\nAdditional models will be excluded if necessary:\n")
```

Another example from `sar_multi()`:

```r
message("\n", paste(length(which(is.na(f_nas))), "models could not be fitted and have been excluded from the multi SAR"), "\n")
```

Could be simplified as follows:

```r
message("\n", sum(is.na(f_nas)), " model(s) could not be fitted and have been excluded from the multi SAR, \n")
```

### More than one fit

It would be better to have one function that runs several SAR models without averaging them instead of stacking model with `fit_collection`. I envision something like this:

- `multi_sars()` that fits several sar model;
- then a new function, say `average_sars()`, would perform the averaging. It would take a
`fit_collection` objects or a vectors of character strings as input. If character strings are passed then it would call `muti_sars()` and proceed with the `fit_collection` object returned while this step will be skipped if a `fit_collection` object is passed.

Regarding the SAR models, 20 is a lot, which is good! What would help are functions that would remind the user what models are available. I would create two small functions (see below) and include Table 1 of your ms as a `rda` file:

```r
sars_models <- function() {
  c("power","powerR","epm1","epm2","p1","p2","expo","koba","mmf","monod","negexpo","chapman","weibull3","asymp","ratio","gompertz","weibull4","betap","heleg", "linear")
}

display_sars_models <- function() {
  # display table 1 of the manuscript
}
```

This allows the user to use number instead of character strings to identify models.

### Declare list/matrices/vectors with size when possible

For instance, in the code below (from `coleman.R`)

```r
s_alp <- c()
s_hat <- c()
for (j in seq_along(ra)){
  for (i in seq_along(abun)){
    s_alp[i] <- sa(ra[j],abun[i])
  } #eo i
  s_hat[j] <- tot_sp - sum(s_alp)
} #eo j
```

You should better declare `s_alp` and `s_hat` as the size as known.

```r
s_alp <- length(abun)
s_hat <- length(ra)
for (j in seq_along(ra)){
  for (i in seq_along(abun)){
    s_alp[i] <- sa(ra[j],abun[i])
  } #eo i
  s_hat[j] <- tot_sp - sum(s_alp)
} #eo j
```

### Exclude inst/refs from the build?

I was wondering if the refs added in `inst/refs` are supposed to be included in the
package. 

Let me know if anything is not clear enough and if I can be of any help!

## Session info

<details>

```r
R>> sessionInfo()
R version 3.5.1 (2018-07-02)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Debian GNU/Linux buster/sid

Matrix products: default
BLAS: /usr/lib/x86_64-linux-gnu/openblas/libblas.so.3
LAPACK: /usr/lib/x86_64-linux-gnu/libopenblasp-r0.3.3.so

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C               LC_TIME=en_CA.UTF-8        LC_COLLATE=en_US.UTF-8     LC_MONETARY=en_CA.UTF-8
 [6] LC_MESSAGES=en_US.UTF-8    LC_PAPER=en_CA.UTF-8       LC_NAME=C                  LC_ADDRESS=C               LC_TELEPHONE=C
[11] LC_MEASUREMENT=en_CA.UTF-8 LC_IDENTIFICATION=C

attached base packages:
[1] stats     graphics  grDevices utils     base


other attached packages:
[1] magrittr_1.5        graphicsutils_1.2-0 knitr_1.20          rmarkdown_1.10      devtools_1.13.6     inSilecoMisc_0.1.2

loaded via a namespace (and not attached):
 [1] compiler_3.5.1  backports_1.1.2 rprojroot_1.3-2 tools_3.5.1     htmltools_0.3.6 withr_2.1.2     Rcpp_0.12.18    memoise_1.1.0   stringi_1.2.4
[10] methods_3.5.1   stringr_1.3.1   digest_0.6.17   evaluate_0.11
```

</details>

### CODE REVIEW

**Comment by KevCaz** [comment]
I can open another PR just for the white space and once accepted merge the master and update this PR. That being said, you can also deal with this yourself. For example you could use [`formatR`](https://cran.r-project.org/web/packages/formatR/index.html), update the master and then I could update this PR with the master merged. Let me know what is the best option for you!

**Comment by mkborregaard** [comment]
To be clear, I'm the Ecography editor, and have no other relationship to this project.

**Comment by KevCaz** [comment]
I agree that my the cleanup of the whitespace does not make it easy to review the PR but to me, what matters the most, is what I wrote here and in my review, not the small edits in the code. Actually I wouldn't mind if the authors ignore my PR and follow my recommendation by editing the code them-selves. 
I did not add any feature in this PR, just edited very small portions of the code (and unfortunately I removed many whitespace making the PR very bloated!). 

@txm676 and @fguilhaumon, let me know what you want me to do with this PR, more than happy to proceed as @mkborregaard recommended.

**Comment by txm676** [comment]
@KevCaz @mkborregaard 

Sorry I only just received a notification of this PR and general conversation today. It looks very helpful so thanks. I am very busy today but will check through it in detail tomorrow

**Comment by KevCaz** [comment]
My bad, I did not mention your name in the PR.

**Pull request merged**
